import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View } from 'react-native';
import CountDown from 'react-native-countdown-component';
import { PushNotificationIOS } from 'react-native';
import PushNotification from 'react-native-push-notification';
import styles from './style';
const instructions = Platform.select({
    ios: 'Hello ios user. You will get push notification after a few moments',
    android: 'Hello android user; \nYou will get push notification after a few moments'
});
export default class pushControler extends Component {
    componentDidMount() {
        PushNotification.configure({
            onRegister: function (token) {
                console.log('TOKEN:', token);
            },
            onNotification: function (notification) {
                console.log('NOTIFICATION:', notification);
                notification.finish(PushNotificationIOS.FetchResult.NoData);
            },
            senderID: "789350230773",
            popInitialNotification: true,
            requestPermissions: true,
            permissions: {
                alert: true,
                badge: true,
                sound: true,
            },
        });
        PushNotification.requestPermissions();

        PushNotification.localNotificationSchedule({
            /* Android Only Properties */
            id: '0', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
            ticker: "My Notification Ticker", // (optional)
            autoCancel: true, // (optional) default: true
            largeIcon: "ic_launcher", // (optional) default: "ic_launcher"
            smallIcon: "ic_notification", // (optional) default: "ic_notification" with fallback for "ic_launcher"
            bigText: "My big text that will be shown when notification is expanded", // (optional) default: "message" prop
            subText: "This is a subText", // (optional) default: none
            color: "red", // (optional) default: system default
            vibrate: true, // (optional) default: true
            vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
            tag: 'some_tag', // (optional) add tag to message
            group: "group", // (optional) add group to message
            ongoing: false, // (optional) set whether this is an "ongoing" notification
            priority: "high", // (optional) set notification priority, default: high
            visibility: "private", // (optional) set notification visibility, default: private
            importance: "high", // (optional) set notification importance, default: high
            //... You can use all the options from localNotifications
            message: "My Notification Message", // (required)
            date: new Date(Date.now() + (10 * 1000))
        });
    }
    render() {
        return (
            <View style={styles.container}>
                <Text style={styles.welcome}>Welcome to React Native!</Text>
                <Text style={styles.instructions}>{instructions}</Text>
                <CountDown
                    until={10}
                    // onFinish={() => alert('finished')}
                    // onPress={() => alert('hello')}
                    size={20}
                />
            </View>
        );
    }
}